### ISSUE TITLE
Could you run this test in node only?

### ISSUE THREAD

**Issue by windmaomao** [fisker/create-file-list#1134]
I'm just curious how did you pass the test, is it a browser test? Thanks.

**Comment by fisker** [comment]
Yes, the tests can run in Node.js with jsdom, but it's not "real", it's a browser feature, why not test in chrome?

**Comment by fisker** [comment]
It run in Node.js, check latest CI log https://github.com/fisker/create-file-list/runs/2258741626#step:7:4
