### ISSUE TITLE
I can create FileList() object from image in folder?

### ISSUE THREAD

**Issue by anankuntakamdev** [fisker/create-file-list#1197]

**Comment by fisker** [comment]
Do you mean  in Node.js ? This lib is designed to use in browser.

If it's in browser, you need to get a `File` or `Blob` first, using `FileReader` or `fetch` or something else .

**Comment by anankuntakamdev** [comment]
Yes, in the browser.

I stored multiple images in the system file, using move_uploaded_file php.
Then I wanted to retrieve the multiple images and store it in the formData() oject to add, delete, edit the image again.
Could this lib help me, or do you have any other recommended methods?

This is my need, but I can't find a way to do it.
https://stackoverflow.com/questions/67496606/how-to-retrieve-multiple-images-from-file-system-to-formdata-object-or-filelis
https://stackoverflow.com/questions/42720360/jquery-add-file-object-to-filelist-object/67496539#67496539

**Comment by fisker** [comment]
https://github.com/fisker/set-input-files

**Comment by anankuntakamdev** [comment]
thank
Sorry i'm a beginner
Do you have an example for setInputFiles (input, [file])?
Specifically, Array <file>, how do I get it?

**Comment by fisker** [comment]
I'm sorry. Can't help.

**Comment by anankuntakamdev** [comment]
> I'm sorry. Can't help.

thank 
I have tried and tried it and got the following error TT.
https://github.com/fisker/set-input-files/issues/1387
